version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    # Group updates for easier review
    groups:
      development-dependencies:
        patterns:
          - "rubocop*"
          - "brakeman"
          - "debug"
          - "web-console"
      test-dependencies:
        patterns:
          - "capybara"
          - "selenium-webdriver"
          - "minitest*"
          - "simplecov*"
      rails-dependencies:
        patterns:
          - "rails"
          - "turbo-rails"
          - "stimulus-rails"
          - "importmap-rails"
    # Security updates should be separate
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "gem"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
    reviewers:
      - "@sjnims"
    # Ignore specific versions if needed
    ignore:
      # Example: Ignore Rails 8.1 until ready
      # - dependency-name: "rails"
      #   versions: ["8.1.x"]
    
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "@stevenims"

  # JavaScript dependencies (if using npm/yarn in future)
  # - package-ecosystem: npm
  #   directory: "/"
  #   schedule:
  #     interval: weekly
  #     day: monday
  #     time: "09:00"
  #     timezone: "America/New_York"
  #   open-pull-requests-limit: 5
  #   groups:
  #     development-dependencies:
  #       dependency-type: "development"
  #     production-dependencies:
  #       dependency-type: "production"
  #   commit-message:
  #     prefix: "npm"
  #     include: "scope"
  #   labels:
  #     - "dependencies"
  #     - "javascript"

# Security alerts configuration
registries:
  # Add private registries if needed
  # ruby-gems-server:
  #   type: rubygems-server
  #   url: https://rubygems.your-company.com
  #   token: ${{ secrets.RUBYGEMS_TOKEN }}

# Enable security updates
enable-beta-ecosystems: true